import { App } from 'cdk8s';
import {BitwardenChart} from "./bitwarden";
import {BookstackChart} from "./bookstack";
import {CiaoChart} from "./ciao";
import {CyberChefChart} from "./cyberchef";
import {FlexGetChart} from "./flexget";
import {GapsChart} from "./gaps";
import {GrafanaChart} from "./grafana";
import {GrocyChart} from "./grocy";
import {HeimdallChart} from "./heimdall";
import {HomeAssistantChart} from "./homeassistant";
import {HomerChart} from "./homer";
import {JackettChart} from "./jackett";
import {VsCodeChart} from "./vscode";

const app = new App();
new BitwardenChart(app, 'bitwarden');
new BookstackChart(app, 'bookstack');
new CiaoChart(app, 'ciao');
new CyberChefChart(app, 'cyberchef');
new FlexGetChart(app, 'flexget');
new GapsChart(app, 'gaps');
new GrafanaChart(app, 'grafana');
new GrocyChart(app, 'grocy');
new HeimdallChart(app, 'heimdall');
new HomeAssistantChart(app, 'homeassistant');
new HomerChart(app, 'homer');
new JackettChart(app, 'jackett');
new VsCodeChart(app, 'vscode');

app.synth();
